[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "plox_tokentype"
version = "0.1.0"
description = "Description of my package"
dependencies = [
    "pytest"
]
